"""
cargo_label_client.py
------------------------
Kargo etiketi (barkod) servislerinin SAF HTTP wrapper katmanı. Bu modül
BİLEREK DB'ye dokunmaz, caching/idempotency yapmaz, statü kontrolü yapmaz --
tüm bu orkestrasyon (tekli + toplu, önbellek, statü kuralı) cargo_label_service.py
içinde. Burada sadece "API'ye doğru istek nasıl atılır, cevap nasıl parse
edilir" var (trendyol_qna_client.py / hb_qna_client.py ile aynı desen).

CONFIRMED (12.09.2026 Faz 0, resmi dokümantasyon):

Trendyol -- SADECE "Trendyol Öder" modelinde (TEX / Aras Kargo ortak etiket
sürecinde) çalışır. Satıcı Öder modelinde bu API'ler devre dışıdır (Trendyol
dokümantasyonu: "Label should be generated by the seller"). Sidar'ın
mağazası Trendyol Öder kullanıyor (12.09.2026 onayı).
  POST /integration/sellers/{sellerId}/common-label/{cargoTrackingNumber}
       Body: {"format": "ZPL", "boxQuantity": N, "volumetricHeight": X}
       200 -> başarılı, GÖVDE YOK. 400 -> geçersiz cargoTrackingNumber.
       401 -> kimlik bilgisi hatası.
  GET  aynı URL -> {"data": [{"label": "^XA...^XZ", "format": "ZPL"}]}
       Tek koli -> tek etiket; çoklu koli -> çoklu etiket. SADECE ZPL formatı var.
  https://developers.trendyol.com/v2.0/docs/common-label-barcode-request-createcommonlabel
  https://developers.trendyol.com/v2.0/docs/common-label-getting-created-common-label-getcommonlabel

Hepsiburada -- HepsiJet ortak barkod (Sidar'ın mağazası HepsiJet kullanıyor):
  GET /packages/merchantid/{merchantId}/packagenumber/{packageNumber}/labels
  https://developers.hepsiburada.com/hepsiburada/reference/ortak-barkod-olusturma
  CONFIRMED (canlı test, 13.09.2026): response şeması --
    {"format": "base64zpl", "data": [<base64-encoded ZPL>, ...],
     "description": "...", "code": "100"|diğer, "hasMerchantMutualBarcode": bool}
  Şema normalizasyonu (base64 çözme, Trendyol ile ortak iç formata çevirme)
  cargo_label_service._parse_hb_label_response() içinde -- bu modül (client)
  bilerek ham response'u olduğu gibi döndürmeye devam ediyor (saf HTTP
  wrapper prensibi).
  Paket henüz oluşturulmamışsa (status='AwaitingPackage', negatif
  placeholder_id) HB 404 döner -- HepsiburadaLabelError'a çevrilir.
"""

import logging

import requests

from sync_core import hepsiburada_get
from trendyol_client import SUPPLIER_ID, trendyol_get, trendyol_post

logger = logging.getLogger(__name__)

_HB_LABEL_DEBUG_LOGGED = False


class TrendyolLabelError(Exception):
    """Trendyol etiket servislerinden beklenmeyen/boş bir cevap geldiğinde."""


class HepsiburadaLabelError(Exception):
    """Hepsiburada etiket servisinden beklenmeyen/boş bir cevap geldiğinde."""


# ------------------------------------------------------------------
# Trendyol -- createCommonLabel / getCommonLabel
# ------------------------------------------------------------------

def trendyol_create_common_label(cargo_tracking_number, box_quantity=1, volumetric_height=None):
    """Ortak etiket barkod talebi oluşturur (createCommonLabel).

    Başarılı olursa None döner (servis 200 + boş gövde döner, bkz. modül
    docstring'i) -- etiketin KENDİSİ bu çağrıdan gelmez, ayrıca
    trendyol_get_common_label() ile ÇEKİLMESİ gerekir (Trendyol'un
    iki-aşamalı akışı, bkz. Order Process Flow dokümantasyonu).
    """
    body = {"format": "ZPL", "boxQuantity": box_quantity}
    if volumetric_height is not None:
        body["volumetricHeight"] = volumetric_height
    path = f"/integration/sellers/{SUPPLIER_ID}/common-label/{cargo_tracking_number}"
    trendyol_post(path, json_body=body)


def trendyol_get_common_label(cargo_tracking_number):
    """Daha önce create edilmiş ortak etiketi çeker (getCommonLabel).

    Döner: [{"label": "^XA...^XZ", "format": "ZPL"}, ...] -- çoklu koli
    durumunda birden fazla eleman olabilir.

    'data' boşsa (henüz create edilmemiş ya da Trendyol tarafında henüz
    hazır değilse) sessizce [] DÖNDÜRÜLMEZ -- TrendyolLabelError fırlatılır,
    böylece çağıran katman (service) "create çağır" ile "gerçekten hata"yı
    ayırt edebilir."""
    path = f"/integration/sellers/{SUPPLIER_ID}/common-label/{cargo_tracking_number}"
    response = trendyol_get(path)
    labels = (response or {}).get("data") or []
    if not labels:
        raise TrendyolLabelError(
            f"Trendyol getCommonLabel boş döndü (cargoTrackingNumber={cargo_tracking_number}). "
            "Önce trendyol_create_common_label() çağrılmış mı kontrol edin."
        )
    return labels


# ------------------------------------------------------------------
# Hepsiburada -- HepsiJet ortak barkod
# ------------------------------------------------------------------

def hb_fetch_package_labels(package_number):
    """HepsiJet ortak barkod etiketini çeker (ham response, parse etmez --
    şema yorumlama cargo_label_service._parse_hb_label_response()'da).

    CONFIRMED (canlı test, 13.09.2026): response şeması --
    {"format": "base64zpl", "data": [<base64-encoded ZPL>, ...],
     "description": "...", "code": "100", "hasMerchantMutualBarcode": true}

    CONFIRMED (canlı test, 12.09.2026): paket henüz oluşturulmamışsa
    (ör. sipariş 'AwaitingPackage' statüsünde, sync_core.py'nin negatif
    placeholder_id ile işaretlediği durumlar) HB bu endpoint'te 404 döner.
    Ham requests.exceptions.HTTPError sızdırılmaz -- diğer hatalarla aynı
    şekilde ele alınabilmesi için HepsiburadaLabelError'a çevrilir."""
    global _HB_LABEL_DEBUG_LOGGED
    from sync_core import HB_MERCHANT_ID
    path = f"/packages/merchantid/{HB_MERCHANT_ID}/packagenumber/{package_number}/labels"

    try:
        response = hepsiburada_get(path)
    except requests.exceptions.HTTPError as exc:
        status = exc.response.status_code if exc.response is not None else "?"
        raise HepsiburadaLabelError(
            f"Hepsiburada /labels HTTP {status} döndü (packageNumber={package_number}). "
            "404 genellikle paketin henüz oluşturulmadığı (AwaitingPackage) anlamına gelir."
        ) from exc

    if not _HB_LABEL_DEBUG_LOGGED:
        logger.debug(f"[HB LABEL DEBUG] ham response (şema doğrulama amaçlı): {response}")
        _HB_LABEL_DEBUG_LOGGED = True

    if not response:
        raise HepsiburadaLabelError(
            f"Hepsiburada /labels boş döndü (packageNumber={package_number})."
        )
    return response
